version: '3'
services:
  app:
    build:
      args:
        user: sendportal
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sendportal
    container_name: sendportal-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sendportal

  db:
    image: mysql:8.0
    container_name: sendportal-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - sendportal

  nginx:
    image: nginx:alpine
    container_name: sendportal-nginx
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - sendportal

networks:
  sendportal:
    driver: bridge
